---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc vars
      include_vars: vars/vars

    - name: create a vpc
      ec2_vpc_net:
         name: "{{vpc_name}}"
         cidr_block: "{{vpccidr}}"
         region: "{{region}}"
         dns_support: yes
         dns_hostnames: yes
         tenancy: default
         state: "{{state}}"
      register: vpcout

    - name: create a pubsubnet
      ec2_vpc_subnet:
         vpc_id: "{{vpcout.vpc.id}}"
         region: "{{region}}"
         az: "{{zone}}"
         state: "{{state}}"
         cidr: "{{pubsubnet}}"
         map_public: yes
         tags:
           Name: pub_subnet
      register: pubsubout

    - name: create a pvtsubnet
      ec2_vpc_subnet:
         vpc_id: "{{vpcout.vpc.id}}"
         region: "{{region}}"
         az: "{{zone}}"
         state: "{{state}}"
         cidr: "{{pvtsubnet}}"
         tags:
          Name: pvtsubnet
      register: pvtsubout

    - name: create a internetgateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
          Name: vprofileigw
      register: igwout

    - name: create a pub route_table
      ec2_vpc_route_table:
         vpc_id: "{{vpcout.vpc.id}}"
         region: "{{region}}"
         subnets:
            - "{{pubsubout.subnet.id}}"
         routes:
           - dest: 0.0.0.0/0
             gateway_id: "{{igwout.gateway_id}}"
         tags:
           Name: vprofilepubRT
      register: pubRTout

    - name: create a natgateway
      ec2_vpc_nat_gateway:
       state: "{{state}}"
       region: "{{region}}"
       subnet_id: "{{pubsubout.subnet.id}}"
       wait: yes
       if_exist_do_not_create: true
      register: natgatewatout

    - name: create a pvt routetable
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        subnets:
           - "{{pvtsubout.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{natgatewatout.nat_gateway_id}}"
        tags:
          Name: vprofileprivateRT
      register: pvtRTout

    - debug:
         var: "{{item}}"
      loop:
           -  vpcout.vpc.id
           -  pvtsubout.subnet.id
           -  pubsubout.subnet.id
           -  igwout.gateway_id
           -  natgatewatout.nat_gateway_id
           -  pvtRTout.route_table.id
           -  pubRTout.route_table.id

    - set_fact:
        vpcid: "{{vpcout.vpc.id}}"
        privatesubnetid: "{{pvtsubout.subnet.id}}"
        publicsubnetid: "{{pubsubout.subnet.id}}"
        internetgatewayid: "{{igwout.gateway_id}}"
        natgatewayid: "{{natgatewatout.nat_gateway_id}}"
        privateRoutetableid: "{{pvtRTout.route_table.id}}"
        publicroutetableid: "{{pubRTout.route_table.id}}"
        cacheable: yes

    - name: create a var file for output
      copy:
        content: "vpcid: {{vpcout.vpc.id}}\nprivatesubnetid: {{pvtsubout.subnet.id}}\npublicsubnetid: {{pubsubout.subnet.id}}\ninternetgatewayid: {{igwout.gateway_id}}\nnatgatewayid: {{natgatewatout.nat_gateway_id}}\nprivateRoutetableid: {{pvtRTout.route_table.id}}\npublicroutetableid: {{pubRTout.route_table.id}}"
        dest: var/output_vars
