---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/output_vars
    - vars/prostacksetup
    - vars/vars
  tasks:

   - name: create a keypair
     ec2_key:
       name: vprofile-key
       region: "{{region}}"
     register: keyout

   - name: save the key paiy created
     copy:
       content: "{{keyout.key.private_key}}"
       dest: "./vprofile-key.pem"
       mode: 0600
     when: keyout.changed

   - name: create a ELB security Group


